# Generated by Django 4.2.20 on 2025-03-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_product_hsn_code_alter_product_gst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceitem_set', to='inventory.invoice'),
        ),
    ]
