# Generated by Django 4.2.20 on 2025-04-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hsn_code',
        ),
    ]
