# Generated by Django 4.2.20 on 2025-04-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_multisaletransaction_multisaleitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='multipurchasetransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.multipurchasetransaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.invoice'),
        ),
    ]
