# Generated by Django 4.2.20 on 2025-04-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_payment_multipurchasetransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='multisaletransaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.multisaletransaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
    ]
