# Generated by Django 4.2.20 on 2025-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_invoice_multisaletransaction_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisaleitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='multisaleitem',
            name='quantity_sold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='multisaleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
